name: chat_app
description: "ChatApp"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.1.0

  # Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.4.1

  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^15.1.2

  # Flutter widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^9.1.1

  # A simple package to simplify screen management. When loading any async task, this package prevent the user from interacting with the screen until the async task finishes.
  loader_overlay: ^5.0.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: 0.19.0

  # # Package is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
  intl_utils: ^2.8.8

  # A unified form representation in Dart which aims to simplify form representation and validation in a generic way.
  formz: ^0.8.0

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.7

  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.13.1

  # Flutter plugin for Firebase Auth, enabling authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter.
  firebase_auth: ^5.5.4

  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization and offline support on Android and iOS.
  cloud_firestore: ^5.6.8

  # Flutter plugin for Firebase Database, a cloud-hosted NoSQL database with realtime data syncing across Android and iOS clients, and offline access.
  firebase_database: ^11.3.6

  # Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS.
  firebase_storage: ^12.4.6

  # Custom event transformers inspired by ember concurrency. Built to be used with the bloc state management package.
  bloc_concurrency: ^0.3.0

  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.1.2

  # Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
  hive: ^2.2.3

  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_flutter: ^1.1.0

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # A tool for managing Dart & Flutter repositories with multiple packages (monorepo). Supports automated versioning via Conventional Commits. Inspired by JavaScripts Lerna package.
  melos: ^6.3.2

  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.15

  # The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
  flutter_gen_runner: ^5.10.0

  # A mocking library for Dart, used for creating mock objects in tests.
  mocktail: ^1.0.4

  # A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
  bloc_test: ^10.0.0

  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600

flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/resources/l10n_generated

# Config gen assets
flutter_gen:
  output: lib/core/resources/assets_generated/ # Optional (default: lib/gen/)
  # Optional
  integrations:
    flutter_svg: true
